### ISSUE TITLE
Minimal ram option won't boot under qemu or VirtualBox VM

### ISSUE THREAD

**Issue by gzohop** [pld-linux-org/pld-new-rescue#13]
There is a problem in modules mounting

> \+ echo 'Activating '"'"'rescue'"'"' module'
> Activating 'rescue' module
> \+ /sbin/losetup -o 124 --find --show /root/media/pld-nr/pld-nr-64/rescue.cpi
> [    1.688542] loop_set_status: loop0 () has still dirty pages (nrpages=1)
> losetup: /root/media/pld-nr/pld-nr-64/rescue.cpi: failed to set up loop device: Resource temporarily unavailable
> \+ lodev=
> \+ mkdir -p /.rcd/m/rescue
> \+ mount -t squashfs  /.rcd/m/rescue
> mount: mounting  on /.rcd/m/rescue failed: Invalid argument
> [bootlog.txt](https://github.com/Jajcus/pld-new-rescue/files/2949264/bootlog.txt)

**Comment by gzohop** [comment]
Forgot I was testing th based rescue, not th-2018 ;)
But "Th-2018 1.6" has different problem on VM machine in minimal ram mode:

    6.308291] SQUASHFS error: Unable to read metadata cache entry [a8dfab6]
[    6.309670] SQUASHFS error: Unable to read directory block [a8dfab6:5bb]
[    6.310902] SQUASHFS error: Unable to read metadata cache entry [a8dfab6]
[    6.312371] SQUASHFS error: Unable to read directory block [a8dfab6:5bb]
[    6.318037] SQUASHFS error: Unable to read metadata cache entry [a8dfab6]
[    6.319507] SQUASHFS error: Unable to read directory block [a8dfab6:5bb]
[    6.320957] SQUASHFS error: Unable to read metadata cache entry [a8dfab6]
[    6.322409] SQUASHFS error: Unable to read directory block [a8dfab6:5bb]
[    6.328092] SQUASHFS error: Unable to read metadata cache entry [a8dfab6]
[    6.329572] SQUASHFS error: Unable to read directory block [a8dfab6:5bb]
[    6.331015] SQUASHFS error: Unable to read metadata cache entry [a8dfab6]
[    6.332450] SQUASHFS error: Unable to read directory block [a8dfab6:5bb]

[bootlog-4.19.log](https://github.com/Jajcus/pld-new-rescue/files/2950089/bootlog-4.19.log)

**Comment by arekm** [comment]
Try 20211017.

**Comment by arekm** [comment]
No answers.
