### ISSUE TITLE
New Rescue CD for 2020

### ISSUE THREAD

**Issue by drmarwat** [pld-linux-org/pld-new-rescue#17]
Is there any plans to release a new rescue CD for PLD ? the existing one is two years old and lot has changed since then. A fresh CD would be great for those who wants to do a fresh install of PLD

**Comment by Jajcus** [comment]
I am not active in the PLD any more, so someone else would have to take over this project.

**Comment by glensc** [comment]
20210209 was released 5 minutes ago:

- https://github.com/pld-linux-org/pld-new-rescue/releases/tag/th-current-20210209

try and close the issue if successful!
