### ISSUE TITLE
PLD New Rescue Th-20210209 - not finishing startup with Hyper-V 2012R2 Gen.2 VM

### ISSUE THREAD

**Issue by PekDar** [pld-linux-org/pld-new-rescue#18]
The PLD New Rescue Th-20210209 is not finishing start on Hyper-V 2012R2 VM Gen. 2. when you pick All in RAM from boot menu.
It holds indefinitely with service:
[OK] Finished Update UTMP about System Runlevel Changes.

With minimum RAM
Kernel will panic, so dropping to shell.

**Comment by arekm** [comment]
Wasn't that this bug? "[bug] x86_64 version has first console on tty2 and not on tty1"

Try 20211017 version.

**Comment by PekDar** [comment]
Well now it's a bit better I think but still running process is not finishing.
When I pick All in RAM from boot menu it breaks on:
![image](https://user-images.githubusercontent.com/83333921/138232610-07622162-09b6-408f-8e43-4b50dc162b82.png)

With minimum RAM selected on boot menu it not finishing also:
![image](https://user-images.githubusercontent.com/83333921/138232809-1d5b1644-edd8-41a9-988d-eb922aaf26c1.png)

**Comment by arekm** [comment]
How much of ram do you assign to that VM? (and what happens if more is assigned)

**Comment by PekDar** [comment]
Now is assigned 2GB with dynamically option enabled with scope of min.: 1GB and max.: 3GB
I'll take a tests with more RAM assigned and I'll disable dynamic option. I'll let you know soon.

**Comment by PekDar** [comment]
With assigned 2GB RAM and disabled "dynamic memory" option and selected "All in RAM" from boot menu - works! :)

But with minimum RAM selected it still has same problem.
![image](https://user-images.githubusercontent.com/83333921/138236560-0757c9e2-c8e2-4d38-b140-41b1ea0045c4.png)

**Comment by arekm** [comment]
Minimal ram option works like this:
- load loop and usb-storage modules
- start udevd
- storage devices should now appear in the system
- try to mount fs from storage device that looks like our rescue base system storage (based on UUID)

It looks like it fails - it doesn't see or mount that storage.

Try dmesg, blkid, ls /sys/block to see if there are any storage devices available.

The device should have UUID "2021-10-17-11-40-39-38" (for x86_64 20211017 image).

**Comment by arekm** [comment]
Also output from running rcd (all in memory) would be interesting:
````
lspci -vmm -nn -vk -nn

blkid
````

and if blkid shows up our UUID (or similar that starts with 2021-10..)

````
udevadm info -a -n /dev/that-device | grep DRIVERS
````


You can also test http://carme.pld-linux.org/~arekm/rcd-test-1.iso which prints more errors in case of failure.

**Comment by PekDar** [comment]
> Minimal ram option works like this:
> 
>     * load loop and usb-storage modules
> 
>     * start udevd
> 
>     * storage devices should now appear in the system
> 
>     * try to mount fs from storage device that looks like our rescue base system storage (based on UUID)
> 
> 
> It looks like it fails - it doesn't see or mount that storage.
> 
> Try dmesg, blkid, ls /sys/block to see if there are any storage devices available.
> 
> The device should have UUID "2021-10-17-11-40-39-38" (for x86_64 20211017 image).

Well, in the state where it stops, my keyboard just not works, so I can't type any command in this case.

**Comment by PekDar** [comment]
> Also output from running rcd (all in memory) would be interesting:
> 
> ```
> lspci -vmm -nn -vk -nn
> 
> blkid
> ```
> 
> and if blkid shows up our UUID (or similar that starts with 2021-10..)
> 
> ```
> udevadm info -a -n /dev/that-device | grep DRIVERS
> ```
> 
> You can also test http://carme.pld-linux.org/~arekm/rcd-test-1.iso which prints more errors in case of failure.

With command: #> lspci -vmm -nn -vk -nn  , nothing happend
![image](https://user-images.githubusercontent.com/83333921/138268918-f16aaf8e-9d4e-42c4-a5da-f6ddbc6f94aa.png)

With command: #> blkid
![image](https://user-images.githubusercontent.com/83333921/138269025-d1eaff36-75f3-4f5c-810f-f6ce43df934f.png)

With command: #> udevadm info -a -n /dev/sr0 | grep DRIVERS
![image](https://user-images.githubusercontent.com/83333921/138269383-4342d795-1801-4214-abb4-2ffac55105d6.png)

**Comment by PekDar** [comment]
I've took test with http://carme.pld-linux.org/~arekm/rcd-test-1.iso
With Full works as expected.
But with minimal not works and my keyboard not work also.
![image](https://user-images.githubusercontent.com/83333921/138271019-c79f7b57-0bc4-410c-aa0b-33e5c3ea3e8b.png)

**Comment by arekm** [comment]
Try http://carme.pld-linux.org/~arekm/rcd-test-2.iso with minimal ram option.

**Comment by arekm** [comment]
Ping?

**Comment by PekDar** [comment]
I was very busy, sorry for delay, I'll check test-2 image today

**Comment by PekDar** [comment]
The rcd-test-2.iso works as expected with minimal and full.
Good job!
Will be official update with new release ?

**Comment by arekm** [comment]
There will be at some point. For now I'm leaving rcd-test-2.iso at above url if anyone needs this before next release comes up.

**Comment by arekm** [comment]
Thanks!

**Comment by arekm** [comment]
There is new iso with this fix included. 
https://github.com/pld-linux-org/pld-new-rescue/releases/tag/th-current-20220130
