### ISSUE TITLE
root auto login

### ISSUE THREAD

**Issue by spidero** [pld-linux-org/pld-new-rescue#5]
What do you think about an automatic root login?

**Comment by Jajcus** [comment]
Automatic root login via what means? VGA console? Serial console?

What problem would that solve?

Please note, that this system may be used in various different environments (from embedded PC machines to auto-deployed cloud instances) , not every as secure as others.

**Comment by spidero** [comment]
On vga console, no everyone know that root password is pld. On the other hand leaving default password in auto-deployment cloud instances is more or less security by obscurity.

**Comment by Jajcus** [comment]
The default password is not considered security feature. No root password would, indeed, not change security much, but feels somehow unnatural. And most similar systems do the same – provide simple password related to the project.

**Comment by gzohop** [comment]
Maybe root autologin by optional parameter?

https://github.com/Jajcus/pld-new-rescue/pull/9/commits/6022eca01073d1f8781f180e76daa905452559a9

**Comment by Jajcus** [comment]
6022eca applied. Thanks.
