### ISSUE TITLE
ttyS2 as secure terminal

### ISSUE THREAD

**Issue by gzohop** [pld-linux-org/pld-new-rescue#7]
Hi
Is it possible to add ttyS2 to /etc/securetty?

**Comment by Jajcus** [comment]
Sure :)

**Comment by Jajcus** [comment]
Hmmm… why do you need this? /etc/securetty comes from PLD 'setup' package. I can add ttyS2 (tts/2) there, but it feels somehow arbitrary change.

**Comment by gzohop** [comment]
On some supermicro boards, ipmi console is at ttyS2(ttyS0 is backpanel port, ttyS1 is on-board header port and by default ipmi goes to ttyS2)

**Comment by Jajcus** [comment]
Added. Can you test this, please?

**Comment by gzohop** [comment]
Yes, I should be able to test it by the evening.

**Comment by gzohop** [comment]
I't works, thanks;)

Sorry for delay, the only supermicro board available for testing turned out to have broken ipmi module ;)
